
    import { Switch,Button } from "std-widgets.slint";

    export component AppWindow inherits Window {
    in-out property <bool> active: false;
    in-out property <string> autostart: "Add to Autostart";
    callback add_to_autostart();
    callback change_active();
    callback save_config();
    callback text_to_autostart();
    icon: @image-url("../assets/app_icon.png");
    title: "VG out";
    width: 300px;
    height: 330px;
    background: #b3e0ff;
    HorizontalLayout {
        alignment: center;
        visible: true;
        VerticalLayout {
            alignment: LayoutAlignment.center;
            spacing: 15px;
            HorizontalLayout {
                spacing: 25px;
                cover_image := Image {
                    source: @image-url("../assets/Riot_Vanguard_Logo_Sep_2024.svg");
                    width: 45px;
                    height: 50px;
                    image-fit: ImageFit.fill;
                    image-rendering: ImageRendering.smooth;
                }

                VerticalLayout {
                    padding: 25px;
                    sw := Switch {
                        width: 50px;
                        checked <=> root.active;
                        enabled: true;
                        height: 20px;
                        text: self.checked ? "Active" : "Inactive";
                        toggled => {
                            root.change_active();
                        }
                    }
                }

                states [
                    active when active: {
                        cover_image.colorize: #ff534a;
                    }
                    inactive when !active: {
                        cover_image.colorize: #4d4d4d;
                    }
                ]
            }

            Button {
                width: root.width - 50px;
                height: 30px;
                text: "Save";
                clicked => {
                    root.save_config();
                }
            }

            button_autostart := Button {
                width: root.width - 50px;
                height: 30px;
                text: root.autostart;
                clicked => {
                    root.add_to_autostart();
                }
               
            }

            Button {
                width: root.width - 50px;
                height: 30px;
                text: "Infos";
                clicked => {
                    popup.show();
                }
            }
        }

        popup := PopupWindow {
            close-policy: no-auto-close;
            x: 5px;
            y: 5px;
            width: root.width - 10px;
            height: root.height - 10px;
            Rectangle {
                background: #ffffff;
                width: parent.width;
                height: parent.height;
                VerticalLayout {
                    HorizontalLayout {
                        padding: 15px;
                        alignment: end;
                        Button {
                            text: "✕";
                            width: 30px;
                            height: 30px;
                            clicked => {
                                popup.close();
                            }
                        }
                    }

                    HorizontalLayout {
                        alignment: center;
                        VerticalLayout {
                            text := VerticalLayout {
                                alignment: center;
                                padding: 20px;
                                spacing: 5px;
                                Text {
                                    text: "General Terms of Service";
                                    font-size: 12pt;
                                    horizontal-alignment: center;
                                }

                                Text {
                                    text: "Introduction";
                                    font-size: 10pt;
                                    horizontal-alignment: center;
                                }

                                Text {
                                    text: "When you are a user of Mega Cloud (whether a free user, or on a Pro or Business plan with MEGA VPN and MEGA PASS bundled for free), and/or of MEGA S4, your agreement for all these services is with Mega Privacy LLC (Hungarian Cg. 13-09-239012 with its registered office at Templom utca 17, 2161 Csomàd, Hungary)";
                                    wrap: word-wrap;
                                    font-size: 8pt;
                                    horizontal-alignment: center;
                                }
                            }

                            link_buttons := VerticalLayout {
                                padding-top: 15px;
                                padding-bottom: 15px;
                                spacing: 5px;
                                HorizontalLayout {
                                    alignment: center;
                                    Button {
                                        width: 150px;
                                        height: 30px;
                                        text: "WebSite";
                                    }
                                }

                                HorizontalLayout {
                                    alignment: center;
                                    Button {
                                        width: 150px;
                                        height: 30px;
                                        text: "WebSite";
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
